[package]
name = "lockfree_snowflake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dev-dependencies]
strum_macros = "0.25"
mockall = "0.11"
strum = "0.25"


[dependencies]
chrono = "0.4"